Influxdb setup

diff --git a/deployment/influxdb-setup.yaml b/deployment/influxdb-setup.yaml
--- a/deployment/influxdb-setup.yaml
+++ b/deployment/influxdb-setup.yaml
@@ -1,29 +1,36 @@
 apiVersion: batch/v1
 kind: Job
 metadata:
-  name: influxdb-setup
+  name: bash-influx-setup-job
   namespace: cerebral
 spec:
   template:
     spec:
-      restartPolicy: Never
       containers:
-        - name: create-credentials
-          image: influxdb:latest
-          command:
-            - influx
-          args:
-            - setup
-            - --host
-            - http://10.0.0.4:8086
-            - --bucket
-            - manufacturing
-            - --org
-            - InfluxData
-            - --password
-            - s1$mpl3p4ssw0rd
-            - --username
-            - admin
-            - --token
-            - secret-token
-            - --force
+      - name: bash-job
+        image: influxdb:latest
+        command: ["/bin/bash", "-c"]
+        args:
+        - |
+          #!/bin/bash
+
+          # Run the influx setup command and capture any output and error
+          output=$(influx setup --host http://influxdb.contoso-motors.svc.cluster.local:8086 --bucket manufacturing --org InfluxData --password ArcPassword123!! --username admin --token secret-token --force 2>&1)
+
+          # If the command was successful, print the output and exit
+          if [ $? -eq 0 ]; then
+            echo "$output"
+            exit 0
+          fi
+
+          # If the command failed, check if it's because the instance is already set up
+          if echo "$output" | grep -q "Error: instance has already been set up"; then
+            echo "InfluxDB is already set up."
+            exit 0
+          else
+            # If the command failed for any other reason, print the output and exit with a failure status
+            echo "$output"
+            exit 1
+          fi
+      restartPolicy: Never
+  backoffLimit: 4
